/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { SimpleStorage } from "./SimpleStorage";
export type { Voting } from "./Voting";
export * as factories from "./factories";
export { SimpleStorage__factory } from "./factories/SimpleStorage__factory";
export { Voting__factory } from "./factories/Voting__factory";
